### ISSUE TITLE
Facing Issue when closing the browser 

### ISSUE THREAD

**Issue by git96039** [sbernheim/eyes-cucumber-examples#1]
Hi,
I am facing Issue while closing eyes batch  i.e browsers are not closing automatically and also test results not consolidated

    @AfterSuite
    public void closeEyesBatch() {
        log.info("Thread ID [{}] Eyes BatchID {} CLOSING", getThreadId(), batchManager.batchId());
        TestResultsSummary results = batchManager.closeEyesBatch();
        log.info("Thread ID [{}] Eyes BatchID {} CLOSED", getThreadId(), batchManager.batchId());
        batchManager.logAllTestResults(results);

    }
 
I am Getting this console error, could you please help me with this 

[main] INFO com.applitools.eyes.selenium.managers.EyesBatchManager - Thread ID [1]<-- EYES BATCH closing

com.applitools.eyes.exceptions.TestFailedException: 'Hover over' of 'all Site'. See details at null

	at com.applitools.eyes.universal.CommandExecutor.throwExceptionBasedOnReason(CommandExecutor.java:353)
	at com.applitools.eyes.universal.CommandExecutor.getResults(CommandExecutor.java:262)
	at com.applitools.eyes.EyesRunner.getAllTestResults(EyesRunner.java:128)
	at com.applitools.eyes.EyesRunner.getAllTestResults(EyesRunner.java:189)
	at com.applitools.eyes.selenium.managers.EyesBatchManager.closeEyesBatch(EyesBatchManager.java:254)
	at com.applitools.eyes.selenium.cucumber.heroku.internet.runner.allTestsRunner.closeEyesBatch(allTestsRunner.java:86)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
	at org.testng.internal.invokers.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:69)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:390)
	at org.testng.internal.invokers.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:325)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:410)
	at org.testng.SuiteRunner.run(SuiteRunner.java:336)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
	at org.testng.TestNG.runSuites(TestNG.java:1114)
	at org.testng.TestNG.run(TestNG.java:1082)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:105)

**Comment by git96039** [comment]
build issue, resolved.
